'use strict'; // code generated by pbf v3.2.1

// DataBlob ========================================

var DataBlob = self.DataBlob = {};

DataBlob.read = function (pbf, end) {
    return pbf.readFields(DataBlob._readField, {uuid: "", id: 0, blob: ""}, end);
};
DataBlob._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.uuid = pbf.readString();
    else if (tag === 2) obj.id = pbf.readVarint();
    else if (tag === 3) obj.blob = pbf.readString();
};
DataBlob.write = function (obj, pbf) {
    if (obj.uuid) pbf.writeStringField(1, obj.uuid);
    if (obj.id) pbf.writeVarintField(2, obj.id);
    if (obj.blob) pbf.writeStringField(3, obj.blob);
};
